#!/usr/bin/env bash
# Generate and install a systemd unit for wherever Dowser actually lives.
#
#   sudo deploy/install-service.sh
#
# Paths and the service user are detected rather than hard-coded, so there is
# nothing to hand-edit. Override the user with DOWSER_USER=someone.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PY="$PROJECT_DIR/.venv/bin/python"
UNIT="/etc/systemd/system/dowser.service"

# SUDO_USER is the human who ran sudo; fall back to whoever we are.
RUN_USER="${DOWSER_USER:-${SUDO_USER:-$(id -un)}}"

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: needs root to write $UNIT — re-run with sudo." >&2
  exit 1
fi

if [ ! -x "$PY" ]; then
  echo "ERROR: no virtualenv at $PY" >&2
  echo "       Run ./run.sh once first so it can build one." >&2
  exit 1
fi

if ! id "$RUN_USER" >/dev/null 2>&1; then
  echo "ERROR: user '$RUN_USER' does not exist." >&2
  echo "       Pass an existing one: sudo DOWSER_USER=youruser $0" >&2
  exit 1
fi

RUN_GROUP="$(id -gn "$RUN_USER")"

# Where downloads land, so the unit can be granted write access to it.
DOWNLOAD_DIR="$PROJECT_DIR/downloads"
if [ -f "$PROJECT_DIR/.env" ]; then
  ENV_DIR="$(grep -E '^\s*DOWNLOAD_DIR=' "$PROJECT_DIR/.env" | tail -1 | cut -d= -f2- | tr -d '"'"'"' ' || true)"
  [ -n "${ENV_DIR:-}" ] && DOWNLOAD_DIR="$ENV_DIR"
fi
case "$DOWNLOAD_DIR" in
  /*) ;;                                   # absolute, use as-is
  *) DOWNLOAD_DIR="$PROJECT_DIR/${DOWNLOAD_DIR#./}" ;;
esac
mkdir -p "$DOWNLOAD_DIR"
chown -R "$RUN_USER:$RUN_GROUP" "$DOWNLOAD_DIR" 2>/dev/null || true

echo "==> Installing dowser.service"
echo "    project:   $PROJECT_DIR"
echo "    user:      $RUN_USER:$RUN_GROUP"
echo "    downloads: $DOWNLOAD_DIR"

cat > "$UNIT" <<UNITFILE
# Generated by deploy/install-service.sh — re-run it after moving the project.
[Unit]
Description=Dowser — finds and downloads video streams from any page
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$RUN_USER
Group=$RUN_GROUP

WorkingDirectory=$PROJECT_DIR
EnvironmentFile=-$PROJECT_DIR/.env
ExecStart=$PY -m app.main

# Restart on any exit, including a crash mid-download. Queued jobs are
# persisted, and interrupted ones re-arm themselves when auto-retry is on.
Restart=always
RestartSec=5

# SIGINT lets uvicorn shut down cleanly so in-flight ffmpeg children are killed
# and partial files are removed rather than left behind.
KillSignal=SIGINT
TimeoutStopSec=30

StandardOutput=journal
StandardError=journal
SyslogIdentifier=dowser

# No core dumps: an OOM kill would otherwise dump a multi-gigabyte process
# image onto the disk of the machine that just ran out of room.
LimitCORE=0

NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectControlGroups=true
ProtectKernelTunables=true
RestrictSUIDSGID=true
ReadWritePaths=$PROJECT_DIR $DOWNLOAD_DIR

[Install]
WantedBy=multi-user.target
UNITFILE

systemctl daemon-reload
systemctl enable --now dowser

echo
if systemctl is-active --quiet dowser; then
  echo "==> dowser is running."
  echo "    Logs:   journalctl -u dowser -f"
  echo "    Stop:   sudo systemctl stop dowser"
else
  echo "==> dowser failed to start. Recent log:" >&2
  journalctl -u dowser -n 20 --no-pager >&2
  exit 1
fi
